=== HinaSiddiqui2020/Testing/xml work/emp.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="emp">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="E">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:element name="e_id" type="xs:int"/>
              <xs:element name="e_name" type="xs:string"/>
              <xs:element name="e_ctn" type="xs:string"/>
              
              <xs:element name="e_address">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="10"/>
                    <xs:maxLength value="40"/>
                  </xs:restriction>                  
                </xs:simpleType>
              </xs:element>


              <xs:element name="e_age">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="4"/> 
                    <xs:maxInclusive value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HinaSiddiqui2020/Testing/xml work/employee.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xml" href="empstyle.xslt"?>
<emp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp.xsd">
  <E>
    <e_id>1</e_id>
    <e_name>zaman</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>asad</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>ammad</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>zaid</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>zaman</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>asad</e_name>
    <e_ctn>4467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>8</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>zaman</e_name>
    <e_ctn>44467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>asad</e_name>
    <e_ctn>467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>zaman</e_name>
    <e_ctn>467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>14</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>asad</e_name>
    <e_ctn>44675</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>30</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>zahid</e_name>
    <e_ctn>44467</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>4</e_age>
  </E>
  <E>
    <e_id>1</e_id>
    <e_name>ali</e_name>
    <e_ctn>44657</e_ctn>
    <e_address>sd-1 north nazimbad karachi </e_address>
    <e_age>6</e_age>
  </E>
  
</emp>
